image: alpine:latest

pages:
  stage: deploy
  before_script:
    - apk add --no-cache make bash curl pandoc openjdk17-jre-headless
    - curl -fsSL https://d2lang.com/install.sh | sh --
    - curl -sL https://raw.githubusercontent.com/babashka/babashka/master/install | bash
  script:
    - bb build
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
